version: '2'

services:
  db:
    image: mysql:5.6
    hostname: db
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"